// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC322B_ztTYpVkccbIKUpW-ZuE_4iV_3cA',
    appId: '1:477514590170:web:e95b75f70820a0801782e3',
    messagingSenderId: '477514590170',
    projectId: 'snapdate-32128',
    authDomain: 'snapdate-32128.firebaseapp.com',
    storageBucket: 'snapdate-32128.firebasestorage.app',
    measurementId: 'G-ZVBBHS749Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQTGzVzfWeRaMVQ3XJG79NH9YNdxQJAfw',
    appId: '1:477514590170:android:d0b29d6c14135d411782e3',
    messagingSenderId: '477514590170',
    projectId: 'snapdate-32128',
    storageBucket: 'snapdate-32128.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNDu8BQG9dmYKt9bPLYJ2UoNO8AEkukFM',
    appId: '1:477514590170:ios:93d65efe7b32556f1782e3',
    messagingSenderId: '477514590170',
    projectId: 'snapdate-32128',
    storageBucket: 'snapdate-32128.firebasestorage.app',
    iosBundleId: 'com.example.snapdate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNDu8BQG9dmYKt9bPLYJ2UoNO8AEkukFM',
    appId: '1:477514590170:ios:93d65efe7b32556f1782e3',
    messagingSenderId: '477514590170',
    projectId: 'snapdate-32128',
    storageBucket: 'snapdate-32128.firebasestorage.app',
    iosBundleId: 'com.example.snapdate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC322B_ztTYpVkccbIKUpW-ZuE_4iV_3cA',
    appId: '1:477514590170:web:bcef29a687b4af951782e3',
    messagingSenderId: '477514590170',
    projectId: 'snapdate-32128',
    authDomain: 'snapdate-32128.firebaseapp.com',
    storageBucket: 'snapdate-32128.firebasestorage.app',
    measurementId: 'G-5FFX1QZPVH',
  );
}
